### ISSUE TITLE
bug: `bulk` throwing an error

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper-adapter-minisearch#15]
Not sure why, but tried to perform a bulk operation using `hyper-nano` on via `search.load` on `hyper-connect` and got a `500`. Documents looked like:

```
{
  _id: 'foo',
  name: 'bar',
  email: 'foo@bar.com'
  favoriteColor: 'yellow'
}
```

So either `bulk` is broken or something isn't acceptable about this doc, as the implementation currently stands.

**Comment by twilson63** [comment]
Ok, I will try to take a look at it this week

**Comment by TillaTheHun0** [comment]
`Minisearch` requires that each document have an `id` field. So for the documents above, that only have an `_id`, `Minisearch` will throw an error.

Since documents being indexed in hyper search will typically be coming from hyper data, which will definitely have an `_id` and not always an `id` field, I think it make sense to set `id` on docs, if not defined. 

> NOTE: this is not the same as `_id` being invalid, as was the case with Elasticsearch, and so `_id` had to be mapped to another field in all occurrences. In the case of `Minisearch`, an `id` just had to be on the document.

**Comment by TillaTheHun0** [comment]
After further research, it looks like `Minisearch` supports providing an [`idField: string` option to the constructor](https://github.com/lucaong/minisearch/blob/4eb53192cd3a2ad78b902554eb32c89c2c25b31f/src/MiniSearch.ts#L402), which defaults to `id`.

So I think I will just set `idField` to be `_id`.
